FROM my_jdk1.8.0_191
MAINTAINER cat
ADD target/34-springcloud-service-zipkin-1.0.0.jar /opt
RUN chmod +x /opt/34-springcloud-service-zipkin-1.0.0.jar
CMD java -jar /opt/34-springcloud-service-zipkin-1.0.0.jar